keys:
  - &roman b1187afda5ba91e07f7ef8aee71604ba8e53bf31
  - &puiterwijk age1jsyhycrf872ksv88qk8lfp3whtjxrr4r3mk0m6fa49evev3pmywsf3aa2r

creation_rules:
  - path_regex: hosts/benefice.testing.profian.com
    key_groups:
    - age:
      - age15mq3msgr00046pd8wnjw7y3xww4p4c3u3vxjvud5gldrrzdsl3msz4rfr8

  - path_regex: hosts/sgx.equinix.try.enarx.dev
    key_groups:
    - age:
      - age1ngtadawwwsemf0uveuzz3ypq0y7e5mqxfclk752tdwre98w4sckq8yxjj5

  - path_regex: hosts/snp.aws.try.enarx.dev
    key_groups:
    - age:
      - age1dfy5tv50luyvf62yqh63r69j6g2l30wqscndyyay02y4kp4glyts8as5hj

  - path_regex: hosts/snp.equinix.try.enarx.dev
    key_groups:
    - age:
      - age1xq3cf6l9l23jqu54s4xqjnex9g04tmuw89tfvk5vwl573njhlscszym3hk

  - path_regex: ca/
    shamir_threshold: 2
    key_groups:
    - age:
      - *puiterwijk
    - age:
      - *puiterwijk
    - pgp:
      - *roman
    - pgp:
      - *roman

  - path_regex: secrets/monitoring_api_token
    key_groups:
    - age:
      # snp.equinix.try.enarx.dev
      - age1xq3cf6l9l23jqu54s4xqjnex9g04tmuw89tfvk5vwl573njhlscszym3hk
      # snp.aws.try.enarx.dev
      - age1dfy5tv50luyvf62yqh63r69j6g2l30wqscndyyay02y4kp4glyts8as5hj
      # sgx.equinix.try.enarx.dev
      - age1ngtadawwwsemf0uveuzz3ypq0y7e5mqxfclk752tdwre98w4sckq8yxjj5
      # benefice.testing.profian.com
      - age15mq3msgr00046pd8wnjw7y3xww4p4c3u3vxjvud5gldrrzdsl3msz4rfr8
      # store.testing.profian.com
      - age12r67ult8s9pcrw0lehsfhsxdn77xj9pxh8ha7tkajtktz4knt5uszvz2df
      # store.staging.profian.com
      - age1cypsxexvv20ps6ysv6vau5ltzz7a3lyfqvxwesndnn7gmwpjvpxspfcjuv
      # store.profian.com
      - age1tl5j36jdl45mwnjffshdv2m6sqelyhga3utqg0e23d7uz8nd0fwqnyzg56
