name: Build
on: [ push, pull_request ]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    strategy:
      matrix:
        output:
        # Drawbridge
        - nixosConfigurations.store-staging.config.system.build.toplevel
        - nixosConfigurations.store-testing.config.system.build.toplevel
        - nixosConfigurations.store.config.system.build.toplevel

        # Steward
        - nixosConfigurations.attest-staging.config.system.build.toplevel
        - nixosConfigurations.attest-testing.config.system.build.toplevel

        # Steward production
        - nixosConfigurations.attest-production-1.config.system.build.toplevel
        - nixosConfigurations.attest-production-2.config.system.build.toplevel
        - nixosConfigurations.attest-production-3.config.system.build.toplevel
        - nixosConfigurations.attest-production-4.config.system.build.toplevel

        # Benefice
        - nixosConfigurations.benefice-testing.config.system.build.toplevel
        - nixosConfigurations.sgx-equinix-try.config.system.build.toplevel
        - nixosConfigurations.snp-aws-try.config.system.build.toplevel
        - nixosConfigurations.snp-equinix-try.config.system.build.toplevel

        # Infrastructure
        - nixosConfigurations.nuc-1.config.system.build.toplevel

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: nixbuild/nix-quick-install-action@v18
      with:
        nix_conf: experimental-features = nix-command flakes
    - uses: cachix/cachix-action@v11
      with:
        name: enarx
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Build ${{ matrix.output }}
      run: nix build -L --show-trace '.#${{ matrix.output }}'

    # TODO: Build and run a VM, test
