name: Build
on: [ push, pull_request ]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    strategy:
      matrix:
        output:
        # Drawbridge
        - nixosConfigurations.store-staging.config.system.build.toplevel
        - nixosConfigurations.store-testing.config.system.build.toplevel
        - nixosConfigurations.store.config.system.build.toplevel

        # Steward
        - nixosConfigurations.attest-staging.config.system.build.toplevel
        - nixosConfigurations.attest-testing.config.system.build.toplevel
        - nixosConfigurations.attest.config.system.build.toplevel

        # Steward production
        - nixosConfigurations.attest-production1.config.system.build.toplevel
        - nixosConfigurations.attest-production2.config.system.build.toplevel
        - nixosConfigurations.attest-production3.config.system.build.toplevel
        - nixosConfigurations.attest-production4.config.system.build.toplevel

        # Benefice
        - nixosConfigurations.benefice-testing.config.system.build.toplevel
        - nixosConfigurations.sgx-equinix-try.config.system.build.toplevel
        - nixosConfigurations.snp-equinix-try.config.system.build.toplevel

        # Infrastructure
        - nixosConfigurations.nuc-1.config.system.build.toplevel

    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v17
    - uses: cachix/cachix-action@v10
      with:
        name: enarx
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Build ${{ matrix.output }}
      run: nix build -L '.#${{ matrix.output }}'

    # TODO: Build and run a VM, test
