name: Deploy
concurrency: staging
on:
  push:
    branches:
    - main
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-20.04
    environment: staging
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v17
    - uses: cachix/cachix-action@v10
      with:
        name: enarx
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Deploy
      # TODO: Reenable https://github.com/profianinc/infrastructure/issues/1
      run: |
        nix develop -c deploy || exit 0
